--------------------------------------------------------
--  ������ ������ - ȭ����-9��-01-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACT_INTEREST
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ACT_INTEREST" 
   (	"INTEREST_ACT" NUMBER, 
	"INTEREST_NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ACT_REPLY
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ACT_REPLY" 
   (	"REP_NUM" NUMBER, 
	"REP_ACT" NUMBER, 
	"REP_PERSON" VARCHAR2(20 CHAR), 
	"REP_DATE" DATE, 
	"REP_CONTENT" VARCHAR2(200 CHAR), 
	"REP_POS" NUMBER, 
	"REP_REF" NUMBER, 
	"REP_DEPTH" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ACT_REWARD
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ACT_REWARD" 
   (	"REWARD_ACT" NUMBER, 
	"REWARD_NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ACTIVITY
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ACTIVITY" 
   (	"ACT_NUM" NUMBER, 
	"ACT_TYPE" NUMBER, 
	"ACT_THUMB" VARCHAR2(200 CHAR), 
	"ACT_POST" VARCHAR2(200 CHAR), 
	"ACT_TITLE" VARCHAR2(200 CHAR), 
	"ACT_HITS" NUMBER, 
	"ACT_ORG" VARCHAR2(20 CHAR), 
	"ACT_TARGET" VARCHAR2(20 CHAR), 
	"ACT_START" DATE, 
	"ACT_END" DATE, 
	"ACT_POP" NUMBER, 
	"ACT_REG" NUMBER, 
	"ACT_FIELD" NUMBER, 
	"ACT_HOME" VARCHAR2(200 CHAR), 
	"ACT_CONTENT" VARCHAR2(2000 CHAR), 
	"ACT_AWARD" NUMBER, 
	"ACT_APPROVE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ADMIN" 
   (	"ADMIN_ID" VARCHAR2(20 CHAR), 
	"ADMIN_PWD" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMM_REPLY
--------------------------------------------------------

  CREATE TABLE "SCOTT"."COMM_REPLY" 
   (	"REP_NUM" NUMBER, 
	"REP_COMM" NUMBER, 
	"REP_PERSON" VARCHAR2(20 CHAR), 
	"REP_DATE" DATE, 
	"REP_CONTENT" VARCHAR2(200 CHAR), 
	"REP_POS" NUMBER, 
	"REP_REF" NUMBER, 
	"REP_DEPTH" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMUNITY
--------------------------------------------------------

  CREATE TABLE "SCOTT"."COMMUNITY" 
   (	"COMM_NUM" NUMBER, 
	"COMM_TYPE" NUMBER, 
	"COMM_TITLE" VARCHAR2(200 CHAR), 
	"COMM_PERSON" VARCHAR2(20 CHAR), 
	"COMM_DATE" DATE, 
	"COMM_HITS" NUMBER, 
	"COMM_CONTENT" VARCHAR2(2000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INTEREST
--------------------------------------------------------

  CREATE TABLE "SCOTT"."INTEREST" 
   (	"INTER_PERSON" VARCHAR2(20 CHAR), 
	"INTER_NUM" NUMBER, 
	"INTER_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORG_USER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ORG_USER" 
   (	"ORG_ID" VARCHAR2(20 CHAR), 
	"ORG_PWD" VARCHAR2(20 CHAR), 
	"ORG_NAME" VARCHAR2(20 CHAR), 
	"ORG_TYPE" NUMBER, 
	"ORG_MANAGER" VARCHAR2(20 CHAR), 
	"ORG_EMAIL" VARCHAR2(200 CHAR), 
	"ORG_PHONE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSON_USER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PERSON_USER" 
   (	"PERSON_ID" VARCHAR2(20 CHAR), 
	"PERSON_PWD" VARCHAR2(20 CHAR), 
	"PERSON_NICK" VARCHAR2(20 CHAR), 
	"PERSON_BIRTH" DATE, 
	"PERSON_EMAIL" VARCHAR2(200 CHAR), 
	"PERSON_PHONE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCRAP
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SCRAP" 
   (	"SCRAP_PERSON" VARCHAR2(20 CHAR), 
	"SCRAP_NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACTIVITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."ACTIVITY_PK" ON "SCOTT"."ACTIVITY" ("ACT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."ADMIN_PK" ON "SCOTT"."ADMIN" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMMUNITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."COMMUNITY_PK" ON "SCOTT"."COMMUNITY" ("COMM_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORG_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."ORG_USER_PK" ON "SCOTT"."ORG_USER" ("ORG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERSON_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PERSON_USER_PK" ON "SCOTT"."PERSON_USER" ("PERSON_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ACTIVITY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ACTIVITY" MODIFY ("ACT_NUM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ACTIVITY" ADD CONSTRAINT "ACTIVITY_PK" PRIMARY KEY ("ACT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ADMIN" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMUNITY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."COMMUNITY" MODIFY ("COMM_NUM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."COMMUNITY" ADD CONSTRAINT "COMMUNITY_PK" PRIMARY KEY ("COMM_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORG_USER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ORG_USER" MODIFY ("ORG_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ORG_USER" ADD CONSTRAINT "ORG_USER_PK" PRIMARY KEY ("ORG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSON_USER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PERSON_USER" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."PERSON_USER" ADD CONSTRAINT "PERSON_USER_PK" PRIMARY KEY ("PERSON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACT_INTEREST
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ACT_INTEREST" ADD CONSTRAINT "ACT_INTEREST_FK1" FOREIGN KEY ("INTEREST_ACT")
	  REFERENCES "SCOTT"."ACTIVITY" ("ACT_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACT_REPLY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ACT_REPLY" ADD CONSTRAINT "ACT_REPLY_FK1" FOREIGN KEY ("REP_ACT")
	  REFERENCES "SCOTT"."ACTIVITY" ("ACT_NUM") ENABLE;
  ALTER TABLE "SCOTT"."ACT_REPLY" ADD CONSTRAINT "ACT_REPLY_FK2" FOREIGN KEY ("REP_PERSON")
	  REFERENCES "SCOTT"."PERSON_USER" ("PERSON_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACT_REWARD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ACT_REWARD" ADD CONSTRAINT "REWARD_FK1" FOREIGN KEY ("REWARD_ACT")
	  REFERENCES "SCOTT"."ACTIVITY" ("ACT_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACTIVITY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ACTIVITY" ADD CONSTRAINT "ACTIVITY_FK1" FOREIGN KEY ("ACT_ORG")
	  REFERENCES "SCOTT"."ORG_USER" ("ORG_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMM_REPLY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."COMM_REPLY" ADD CONSTRAINT "REPLY_FK1" FOREIGN KEY ("REP_COMM")
	  REFERENCES "SCOTT"."COMMUNITY" ("COMM_NUM") ENABLE;
  ALTER TABLE "SCOTT"."COMM_REPLY" ADD CONSTRAINT "REPLY_FK2" FOREIGN KEY ("REP_PERSON")
	  REFERENCES "SCOTT"."PERSON_USER" ("PERSON_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMUNITY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."COMMUNITY" ADD CONSTRAINT "COMMUNITY_FK1" FOREIGN KEY ("COMM_PERSON")
	  REFERENCES "SCOTT"."PERSON_USER" ("PERSON_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INTEREST
--------------------------------------------------------

  ALTER TABLE "SCOTT"."INTEREST" ADD CONSTRAINT "INTEREST_FK1" FOREIGN KEY ("INTER_PERSON")
	  REFERENCES "SCOTT"."PERSON_USER" ("PERSON_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCRAP
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SCRAP" ADD CONSTRAINT "SCRAP_FK1" FOREIGN KEY ("SCRAP_PERSON")
	  REFERENCES "SCOTT"."PERSON_USER" ("PERSON_ID") ENABLE;
  ALTER TABLE "SCOTT"."SCRAP" ADD CONSTRAINT "SCRAP_FK2" FOREIGN KEY ("SCRAP_NUM")
	  REFERENCES "SCOTT"."ACTIVITY" ("ACT_NUM") ENABLE;

--------------------------------------------------------
--  DDL for Sequence ACT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."ACT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence COMMUNITY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."COMMUNITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
